# Build script for Travis CI
#

# use xenial distribution
dist: xenial

# no need to check for oracle's java
language: java
jdk:
  - openjdk8
  - openjdk 11
  - openjdk-ea


# speed up builds by caching maven local repository
# we are also using python via conda/pip
cache:
  directories:
  - "$HOME/.m2/repository"

# as agreed in our SOP
branches:
  only:
  - master
  - development
  # Travis treats pushed tags as branches
  - /^[vV]?\d+\.\d+\.\d+$/ # matches e.g., v1.2.3, 1.2.3, V1.2.3

# added to make logs look cleaner, crisper, certified fresh
before_install: unset _JAVA_OPTIONS 

# as agreed in our SOP, build everything (don't deploy, just try to 'mvn package' locally, which covers unit tests)
script: mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml clean cobertura:cobertura package
# upload code coverage report, generate maven site (javadocs, documentation, static code analysis, etc.)
after_success: 
- bash <(curl -s https://codecov.io/bash)

# upload to maven
deploy:
  # as agreed in our SOP, builds on development branch will deploy to our maven repository after validating
  # the artifact has a proper SNAPSHOT version
  # make sure to skip integration tests! (using -DskipITs)
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles development-build,!release-build --settings .travis.settings.xml deploy -DskipITs
  on:
    branch: development
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
  # as agreed in our SOP, releases are performed by tagging commits,
  # the version string and version of dependencies are validated (no snapshots allowed)
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles !development-build,release-build --settings .travis.settings.xml deploy -DskipITs
  on:
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
    tags: true

# generate maven site
after_deploy:   
  - mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml site 

# change according to your needs, but we recommend to deactivate email notifications
# for now, we configured Travis to send a notification to the #travis-ci Slack channel 
notifications:
  email:
    on_success: never
    on_failure: never
  slack: 
    on_success: never
    on_failure: always
    # edit the following section if you want to get slack notifications
    rooms:
      - secure: "***"
